// === DOM-Elemente ===
export const uiElements = {
  monthSelector: document.getElementById("monthSelector"),
  yearSelector: document.getElementById("yearSelector"),
  prevMonthButton: document.getElementById("prevMonthButton"),
  nextMonthButton: document.getElementById("nextMonthButton"),
  settingsButton: document.getElementById("settingsButton"),
  infoButton: document.getElementById("infoButton"),
  currentMonthButton: document.getElementById("currentMonthButton"),
  closeSettingsButton: document.getElementById("closeSettingsButton"),
  cancelSettingsButton: document.getElementById("cancelSettingsButton"),
  resetSettingsButton: document.getElementById("resetSettingsButton"),
  exportSettingsButton: document.getElementById("exportSettingsButton"),
  exportSettingsLinkInput: document.getElementById("exportSettingsLink"),
  mainView: document.getElementById("mainView"),
  settingsDialog: document.getElementById("settingsDialog"),
  tablesWrapper: document.getElementById("tablesWrapper"),
  messageBox: document.getElementById("message-box"),
  currentMonthYear: document.getElementById("currentMonthYear"),
  detailsDialog: document.getElementById("detailsDialog"),
  detailsCloseButton: document.getElementById("detailsCloseButton"),
  infoDialog: document.getElementById("infoDialog"),
  infoCloseButton: document.getElementById("infoCloseButton"),
  displayMonthCountInput: document.getElementById("displayMonthCount"),
  deadline1InputSettings: document.getElementById("deadline1InputSettings"),
  deadline2InputSettings: document.getElementById("deadline2InputSettings"),
  weekdayCheckboxes: {
    skipMonday: document.getElementById("skipMonday"),
    skipTuesday: document.getElementById("skipTuesday"),
    skipWednesday: document.getElementById("skipWednesday"),
    skipThursday: document.getElementById("skipThursday"),
    skipFriday: document.getElementById("skipFriday"),
    skipSaturday: document.getElementById("skipSaturday"),
    skipSunday: document.getElementById("skipSunday"),
  },
  holidayCheckboxes: {
    skipNewYear: document.getElementById("skipNewYear"),
    skipGoodFriday: document.getElementById("skipGoodFriday"),
    skipEasterMonday: document.getElementById("skipEasterMonday"),
    skipLabourDay: document.getElementById("skipLabourDay"),
    skipAscension: document.getElementById("skipAscension"),
    skipPentecostMonday: document.getElementById("skipPentecostMonday"),
    skipUnityDay: document.getElementById("skipUnityDay"),
    skipReformationDay: document.getElementById("skipReformationDay"),
    skipChristmasEve: document.getElementById("skipChristmasEve"),
    skipChristmasDay: document.getElementById("skipChristmasDay"),
    skipBoxingDay: document.getElementById("skipBoxingDay"),
    skipNewYearsEve: document.getElementById("skipNewYearsEve"),
  },
  formatSelectors: {
    formatCurrentDate: document.getElementById("formatCurrentDate"),
    formatDeadline1: document.getElementById("formatDeadline1"),
    formatDeadline2: document.getElementById("formatDeadline2"),
  },
  copyPrefixInput: document.getElementById("copyPrefix"),
  copySuffixInput: document.getElementById("copySuffix"),
  shortenHolidaysContainer: document.getElementById("shortenHolidaysContainer"),
};
